/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;
import java.util.*;
import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

        Review review1 = new Review("i love banana" , "banana consumer", 4);
        Review review2 = new Review("i love potato" , "potato consumer", 3);
        Review review3 = new Review("i love tomato" , "tomato consumer", 2);

        Review rev1 = new Review("i hate banana", "banana hater", 2);
        Review rev2 = new Review("i hate potato", "potato hater", 3);
        Review rev3 = new Review("i hate tomato", "tomato hater", 1);

        List<Review> review = new ArrayList<>();
        review.add(review1);
        review.add(review2);
        review.add(review3);

        List<Review> rev = new ArrayList<>();
        rev.add(rev1);
        rev.add(rev2);
        rev.add(rev3);

        Restaurant restaurant1 = new Restaurant("shawarmaKing",5,420);
        Restaurant restaurant2 = new Restaurant("shawarmaUniverse", 4, 69);

        System.out.println(restaurant1);
        System.out.println(restaurant2);

        System.out.println("\n");

        restaurant1.addReview(review);
        restaurant2.addReview(rev);

        System.out.println("Restaurant name : "+restaurant1.getName());
        for(int i = 0 ; i<restaurant1.getReview().size() ; i++){
            System.out.println("Review "+(i+1)+" : "+restaurant1.getReview().get(i).getBody());
        }
        System.out.println(restaurant1);
        System.out.println("\n");

        System.out.println("Restaurant name : "+restaurant2.getName());
        for(int i = 0 ; i<restaurant2.getReview().size() ; i++){
            System.out.println("Review "+(i+1)+" : "+restaurant2.getReview().get(i).getBody());
        }
        System.out.println(restaurant2);
    }

}
